// springboot-vue-version/frontend/src/components/TagBadge.vue
<template>
  <router-link v-if="!onRemove" :to="`/tags/${tag.id}`" class="tag-badge">{{ tag.title }}</router-link>
  <span v-else class="tag-badge cursor-pointer" @click="onRemove">{{ tag.title }} <span class="ml-0.5 text-amber-400/60 hover:text-amber-400">×</span></span>
</template>

<script setup>
defineProps({ tag: Object, onRemove: Function })
</script>

<style scoped>
.tag-badge {
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
  border: 1px solid rgba(245,158,11,0.2);
  background: rgba(245,158,11,0.05);
  color: #f59e0b;
  border-radius: 9999px;
  padding: 0.25rem 0.75rem;
  font-size: 0.75rem;
  text-decoration: none;
  transition: border-color 0.15s, background-color 0.15s;
}
.tag-badge:hover {
  border-color: rgba(245,158,11,0.4);
  background: rgba(245,158,11,0.1);
}
</style>

// mern-version/client/src/components/TagBadge.jsx
import { Link } from 'react-router-dom';

function TagBadge({ tag, onRemove }) {
  const baseClass =
    'inline-flex items-center gap-1 rounded-full border border-amber-400/20 bg-amber-400/5 px-2.5 py-1 text-xs font-medium text-amber-400 transition-colors hover:border-amber-400/40 hover:bg-amber-400/10';

  if (onRemove) {
    return (
      <span className={baseClass}>
        {tag.title}
        <button
          type="button"
          onClick={onRemove}
          className="ml-0.5 rounded-full p-0.5 text-amber-400/60 hover:text-amber-400 focus-visible:outline-2 focus-visible:outline-amber-400"
          aria-label={`移除标签 ${tag.title}`}
        >
          ×
        </button>
      </span>
    );
  }

  return (
    <Link
      to={`/tags/${tag._id}`}
      onClick={(e) => e.stopPropagation()}
      className={baseClass}
    >
      {tag.title}
    </Link>
  );
}

export default TagBadge;
